### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by randspace0** [andraantariksa/nfa-to-dfa#1]
- [x] Arrow on start point (Reference https://martin-thoma.com/how-to-draw-a-finite-state-machine/)
- [x] Implement detect if the state is an end state
- [x] Use `doublecircle` shape for end state
- [x] ~~Set using curly bracket~~
- [x] ~~GUI~~

**Comment by randspace0** [comment]
For conveniences, set doesn't have to use curly bracket
We don't have much time for the GUI, instead we implement it using CLI
